# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: "en-US"

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - user-exp-v1

chat:
  auto_reply: true

early_access: false
